language: csharp
dist: trusty
mono: none
dotnet: 4.6.1
install:
- nuget restore AppleReceiptParser.sln
script:
- dotnet build
- dotnet test AppleReceiptParser.Tests/AppleReceiptParser.Tests.csproj
- sonar-scanner
addons:
  sonarcloud:
    organization: "shoshins-github"
    token: $SONAR_TOKEN